// Code generated by protoc-gen-go. DO NOT EDIT.
// source: customer/service.proto

package customer

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	wrappers "github.com/golang/protobuf/ptypes/wrappers"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type CustomerAddRequest struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CustomerAddRequest) Reset()         { *m = CustomerAddRequest{} }
func (m *CustomerAddRequest) String() string { return proto.CompactTextString(m) }
func (*CustomerAddRequest) ProtoMessage()    {}
func (*CustomerAddRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_0035ba4285b3cf75, []int{0}
}

func (m *CustomerAddRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CustomerAddRequest.Unmarshal(m, b)
}
func (m *CustomerAddRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CustomerAddRequest.Marshal(b, m, deterministic)
}
func (m *CustomerAddRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CustomerAddRequest.Merge(m, src)
}
func (m *CustomerAddRequest) XXX_Size() int {
	return xxx_messageInfo_CustomerAddRequest.Size(m)
}
func (m *CustomerAddRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CustomerAddRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CustomerAddRequest proto.InternalMessageInfo

func (m *CustomerAddRequest) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *CustomerAddRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type CustomerAddResponse struct {
	CustomerId           int64    `protobuf:"varint,1,opt,name=CustomerId,proto3" json:"CustomerId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CustomerAddResponse) Reset()         { *m = CustomerAddResponse{} }
func (m *CustomerAddResponse) String() string { return proto.CompactTextString(m) }
func (*CustomerAddResponse) ProtoMessage()    {}
func (*CustomerAddResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_0035ba4285b3cf75, []int{1}
}

func (m *CustomerAddResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CustomerAddResponse.Unmarshal(m, b)
}
func (m *CustomerAddResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CustomerAddResponse.Marshal(b, m, deterministic)
}
func (m *CustomerAddResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CustomerAddResponse.Merge(m, src)
}
func (m *CustomerAddResponse) XXX_Size() int {
	return xxx_messageInfo_CustomerAddResponse.Size(m)
}
func (m *CustomerAddResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CustomerAddResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CustomerAddResponse proto.InternalMessageInfo

func (m *CustomerAddResponse) GetCustomerId() int64 {
	if m != nil {
		return m.CustomerId
	}
	return 0
}

func init() {
	proto.RegisterType((*CustomerAddRequest)(nil), "customer.CustomerAddRequest")
	proto.RegisterType((*CustomerAddResponse)(nil), "customer.CustomerAddResponse")
}

func init() { proto.RegisterFile("customer/service.proto", fileDescriptor_0035ba4285b3cf75) }

var fileDescriptor_0035ba4285b3cf75 = []byte{
	// 232 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0x4b, 0x2e, 0x2d, 0x2e,
	0xc9, 0xcf, 0x4d, 0x2d, 0xd2, 0x2f, 0x4e, 0x2d, 0x2a, 0xcb, 0x4c, 0x4e, 0xd5, 0x2b, 0x28, 0xca,
	0x2f, 0xc9, 0x17, 0xe2, 0x80, 0x89, 0x4b, 0xc9, 0xa5, 0xe7, 0xe7, 0xa7, 0xe7, 0xa4, 0xea, 0x83,
	0xc5, 0x93, 0x4a, 0xd3, 0xf4, 0xcb, 0x8b, 0x12, 0x0b, 0x0a, 0x52, 0x8b, 0x8a, 0x21, 0x2a, 0x95,
	0x2c, 0xb8, 0x84, 0x9c, 0xa1, 0x6a, 0x1d, 0x53, 0x52, 0x82, 0x52, 0x0b, 0x4b, 0x53, 0x8b, 0x4b,
	0x84, 0xf8, 0xb8, 0x98, 0x32, 0x53, 0x24, 0x18, 0x15, 0x18, 0x35, 0x98, 0x83, 0x98, 0x32, 0x53,
	0x84, 0x84, 0xb8, 0x58, 0xf2, 0x12, 0x73, 0x53, 0x25, 0x98, 0x14, 0x18, 0x35, 0x38, 0x83, 0xc0,
	0x6c, 0x25, 0x53, 0x2e, 0x61, 0x14, 0x9d, 0xc5, 0x05, 0xf9, 0x79, 0xc5, 0xa9, 0x42, 0x72, 0x5c,
	0x5c, 0x30, 0x61, 0x4f, 0x98, 0x11, 0x48, 0x22, 0x46, 0x0b, 0x19, 0xb9, 0xf8, 0x61, 0xdc, 0x60,
	0x88, 0xa3, 0x85, 0x5c, 0xb8, 0x98, 0x13, 0x53, 0x52, 0x84, 0x64, 0xf4, 0x60, 0xce, 0xd6, 0xc3,
	0x74, 0x93, 0x94, 0x2c, 0x0e, 0x59, 0x88, 0xbd, 0x4a, 0x0c, 0x42, 0x1e, 0x5c, 0x2c, 0xc9, 0x19,
	0x89, 0x25, 0x42, 0x32, 0x7a, 0x10, 0x3f, 0xeb, 0xc1, 0xfc, 0xac, 0x17, 0x5c, 0x52, 0x94, 0x99,
	0x97, 0x1e, 0x96, 0x98, 0x53, 0x9a, 0x2a, 0x85, 0x57, 0x56, 0x89, 0x41, 0x83, 0xd1, 0x80, 0xd1,
	0x89, 0x2b, 0x0a, 0x1e, 0x80, 0x49, 0x6c, 0x60, 0x75, 0xc6, 0x80, 0x00, 0x00, 0x00, 0xff, 0xff,
	0xb9, 0x8a, 0x9b, 0x55, 0x6b, 0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// CustomerServiceClient is the client API for CustomerService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type CustomerServiceClient interface {
	Add(ctx context.Context, in *CustomerAddRequest, opts ...grpc.CallOption) (*CustomerAddResponse, error)
	Chat(ctx context.Context, opts ...grpc.CallOption) (CustomerService_ChatClient, error)
}

type customerServiceClient struct {
	cc *grpc.ClientConn
}

func NewCustomerServiceClient(cc *grpc.ClientConn) CustomerServiceClient {
	return &customerServiceClient{cc}
}

func (c *customerServiceClient) Add(ctx context.Context, in *CustomerAddRequest, opts ...grpc.CallOption) (*CustomerAddResponse, error) {
	out := new(CustomerAddResponse)
	err := c.cc.Invoke(ctx, "/customer.CustomerService/add", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *customerServiceClient) Chat(ctx context.Context, opts ...grpc.CallOption) (CustomerService_ChatClient, error) {
	stream, err := c.cc.NewStream(ctx, &_CustomerService_serviceDesc.Streams[0], "/customer.CustomerService/chat", opts...)
	if err != nil {
		return nil, err
	}
	x := &customerServiceChatClient{stream}
	return x, nil
}

type CustomerService_ChatClient interface {
	Send(*wrappers.StringValue) error
	Recv() (*wrappers.StringValue, error)
	grpc.ClientStream
}

type customerServiceChatClient struct {
	grpc.ClientStream
}

func (x *customerServiceChatClient) Send(m *wrappers.StringValue) error {
	return x.ClientStream.SendMsg(m)
}

func (x *customerServiceChatClient) Recv() (*wrappers.StringValue, error) {
	m := new(wrappers.StringValue)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// CustomerServiceServer is the server API for CustomerService service.
type CustomerServiceServer interface {
	Add(context.Context, *CustomerAddRequest) (*CustomerAddResponse, error)
	Chat(CustomerService_ChatServer) error
}

// UnimplementedCustomerServiceServer can be embedded to have forward compatible implementations.
type UnimplementedCustomerServiceServer struct {
}

func (*UnimplementedCustomerServiceServer) Add(ctx context.Context, req *CustomerAddRequest) (*CustomerAddResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Add not implemented")
}
func (*UnimplementedCustomerServiceServer) Chat(srv CustomerService_ChatServer) error {
	return status.Errorf(codes.Unimplemented, "method Chat not implemented")
}

func RegisterCustomerServiceServer(s *grpc.Server, srv CustomerServiceServer) {
	s.RegisterService(&_CustomerService_serviceDesc, srv)
}

func _CustomerService_Add_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CustomerAddRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CustomerServiceServer).Add(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/customer.CustomerService/Add",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CustomerServiceServer).Add(ctx, req.(*CustomerAddRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CustomerService_Chat_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(CustomerServiceServer).Chat(&customerServiceChatServer{stream})
}

type CustomerService_ChatServer interface {
	Send(*wrappers.StringValue) error
	Recv() (*wrappers.StringValue, error)
	grpc.ServerStream
}

type customerServiceChatServer struct {
	grpc.ServerStream
}

func (x *customerServiceChatServer) Send(m *wrappers.StringValue) error {
	return x.ServerStream.SendMsg(m)
}

func (x *customerServiceChatServer) Recv() (*wrappers.StringValue, error) {
	m := new(wrappers.StringValue)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

var _CustomerService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "customer.CustomerService",
	HandlerType: (*CustomerServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "add",
			Handler:    _CustomerService_Add_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "chat",
			Handler:       _CustomerService_Chat_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "customer/service.proto",
}
