// Code generated by protoc-gen-go. DO NOT EDIT.
// source: customer-service.proto

package services

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type CustomerAddRequest struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CustomerAddRequest) Reset()         { *m = CustomerAddRequest{} }
func (m *CustomerAddRequest) String() string { return proto.CompactTextString(m) }
func (*CustomerAddRequest) ProtoMessage()    {}
func (*CustomerAddRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_e11e6f9e510dc23e, []int{0}
}

func (m *CustomerAddRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CustomerAddRequest.Unmarshal(m, b)
}
func (m *CustomerAddRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CustomerAddRequest.Marshal(b, m, deterministic)
}
func (m *CustomerAddRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CustomerAddRequest.Merge(m, src)
}
func (m *CustomerAddRequest) XXX_Size() int {
	return xxx_messageInfo_CustomerAddRequest.Size(m)
}
func (m *CustomerAddRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CustomerAddRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CustomerAddRequest proto.InternalMessageInfo

func (m *CustomerAddRequest) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *CustomerAddRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type CustomerAddResponse struct {
	CustomerId           int64    `protobuf:"varint,1,opt,name=CustomerId,proto3" json:"CustomerId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CustomerAddResponse) Reset()         { *m = CustomerAddResponse{} }
func (m *CustomerAddResponse) String() string { return proto.CompactTextString(m) }
func (*CustomerAddResponse) ProtoMessage()    {}
func (*CustomerAddResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_e11e6f9e510dc23e, []int{1}
}

func (m *CustomerAddResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CustomerAddResponse.Unmarshal(m, b)
}
func (m *CustomerAddResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CustomerAddResponse.Marshal(b, m, deterministic)
}
func (m *CustomerAddResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CustomerAddResponse.Merge(m, src)
}
func (m *CustomerAddResponse) XXX_Size() int {
	return xxx_messageInfo_CustomerAddResponse.Size(m)
}
func (m *CustomerAddResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CustomerAddResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CustomerAddResponse proto.InternalMessageInfo

func (m *CustomerAddResponse) GetCustomerId() int64 {
	if m != nil {
		return m.CustomerId
	}
	return 0
}

func init() {
	proto.RegisterType((*CustomerAddRequest)(nil), "services.CustomerAddRequest")
	proto.RegisterType((*CustomerAddResponse)(nil), "services.CustomerAddResponse")
}

func init() { proto.RegisterFile("customer-service.proto", fileDescriptor_e11e6f9e510dc23e) }

var fileDescriptor_e11e6f9e510dc23e = []byte{
	// 169 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0x4b, 0x2e, 0x2d, 0x2e,
	0xc9, 0xcf, 0x4d, 0x2d, 0xd2, 0x2d, 0x4e, 0x2d, 0x2a, 0xcb, 0x4c, 0x4e, 0xd5, 0x2b, 0x28, 0xca,
	0x2f, 0xc9, 0x17, 0xe2, 0x80, 0x72, 0x8b, 0x95, 0x2c, 0xb8, 0x84, 0x9c, 0xa1, 0x6a, 0x1c, 0x53,
	0x52, 0x82, 0x52, 0x0b, 0x4b, 0x53, 0x8b, 0x4b, 0x84, 0xf8, 0xb8, 0x98, 0x32, 0x53, 0x24, 0x18,
	0x15, 0x18, 0x35, 0x98, 0x83, 0x98, 0x32, 0x53, 0x84, 0x84, 0xb8, 0x58, 0xf2, 0x12, 0x73, 0x53,
	0x25, 0x98, 0x14, 0x18, 0x35, 0x38, 0x83, 0xc0, 0x6c, 0x25, 0x53, 0x2e, 0x61, 0x14, 0x9d, 0xc5,
	0x05, 0xf9, 0x79, 0xc5, 0xa9, 0x42, 0x72, 0x5c, 0x5c, 0x30, 0x61, 0x4f, 0x98, 0x11, 0x48, 0x22,
	0x46, 0xe1, 0x5c, 0xfc, 0x30, 0x5e, 0x30, 0xc4, 0x11, 0x42, 0x2e, 0x5c, 0xcc, 0x89, 0x29, 0x29,
	0x42, 0x32, 0x7a, 0x30, 0x57, 0xe9, 0x61, 0x3a, 0x49, 0x4a, 0x16, 0x87, 0x2c, 0xc4, 0x5a, 0x25,
	0x06, 0x27, 0xae, 0x28, 0xb8, 0xaf, 0x92, 0xd8, 0xc0, 0xde, 0x34, 0x06, 0x04, 0x00, 0x00, 0xff,
	0xff, 0xe6, 0x3d, 0xfa, 0xc3, 0x00, 0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// CustomerServiceClient is the client API for CustomerService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type CustomerServiceClient interface {
	Add(ctx context.Context, in *CustomerAddRequest, opts ...grpc.CallOption) (*CustomerAddResponse, error)
}

type customerServiceClient struct {
	cc *grpc.ClientConn
}

func NewCustomerServiceClient(cc *grpc.ClientConn) CustomerServiceClient {
	return &customerServiceClient{cc}
}

func (c *customerServiceClient) Add(ctx context.Context, in *CustomerAddRequest, opts ...grpc.CallOption) (*CustomerAddResponse, error) {
	out := new(CustomerAddResponse)
	err := c.cc.Invoke(ctx, "/services.CustomerService/add", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CustomerServiceServer is the server API for CustomerService service.
type CustomerServiceServer interface {
	Add(context.Context, *CustomerAddRequest) (*CustomerAddResponse, error)
}

// UnimplementedCustomerServiceServer can be embedded to have forward compatible implementations.
type UnimplementedCustomerServiceServer struct {
}

func (*UnimplementedCustomerServiceServer) Add(ctx context.Context, req *CustomerAddRequest) (*CustomerAddResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Add not implemented")
}

func RegisterCustomerServiceServer(s *grpc.Server, srv CustomerServiceServer) {
	s.RegisterService(&_CustomerService_serviceDesc, srv)
}

func _CustomerService_Add_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CustomerAddRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CustomerServiceServer).Add(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/services.CustomerService/Add",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CustomerServiceServer).Add(ctx, req.(*CustomerAddRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _CustomerService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "services.CustomerService",
	HandlerType: (*CustomerServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "add",
			Handler:    _CustomerService_Add_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "customer-service.proto",
}
